# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on: [push]

name: Install and run

jobs:
  Install-and-sk-run:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Install R
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      # Install pandoc
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.7.3' # The pandoc version to download (if necessary) and use.
      - run: echo "# Test" | pandoc -t html
      # Install python
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - run: pip install scikick
      # Run scikick
      - run: |
          sk run -v
          mv report/out_html/ public/
      # Try beta action for deploy by branch
      - name: Set branch name
        id: branch
        run: echo "::set-output name=BRANCH_NAME::${GITHUB_REF##*/}"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: ${( steps.branch.outputs.name }}
